// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx172961UsDAsJe_x8tILlFHLnJQtrWH8',
    appId: '1:892218212037:web:b7418cc3f62abe1a923aac',
    messagingSenderId: '892218212037',
    projectId: 'hezranbotak-77',
    authDomain: 'hezranbotak-77.firebaseapp.com',
    storageBucket: 'hezranbotak-77.firebasestorage.app',
    measurementId: 'G-9BDJG8RZKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUWKF3b6M9KuIlDy6aCkLeOtWLS_70YOM',
    appId: '1:892218212037:android:f6dd0d556a48462f923aac',
    messagingSenderId: '892218212037',
    projectId: 'hezranbotak-77',
    storageBucket: 'hezranbotak-77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8USbXZ31yYmTSg5g6D_if5aT6xSIpIf0',
    appId: '1:892218212037:ios:9a8ef46e756c9920923aac',
    messagingSenderId: '892218212037',
    projectId: 'hezranbotak-77',
    storageBucket: 'hezranbotak-77.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.zran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8USbXZ31yYmTSg5g6D_if5aT6xSIpIf0',
    appId: '1:892218212037:ios:9a8ef46e756c9920923aac',
    messagingSenderId: '892218212037',
    projectId: 'hezranbotak-77',
    storageBucket: 'hezranbotak-77.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.zran',
  );
}
